resolver: lts-20.1
packages:
  - compiler
  - curry-frontend
  - rts
extra-deps:
  - git: https://github.com/LeventErkok/sbv.git
    commit: ff4cc3341fc508abec2991d7a82ab053371ba4f0
  - libBF-0.6.2
  - git: https://github.com/GaloisInc/parameterized-utils.git
    commit: fec28ebeed59930767d5ed7f62be652881c76385
  - set-extra-1.4.1
allow-newer: true
local-bin-path: bin
allow-different-user: true
