resolver: ghc-9.2
packages:
  - compiler
  - curry-frontend
extra-deps:
  - set-extra-1.4.1
  - extra-1.7.10
  - file-embed-0.0.15.0
  - network-uri-2.6.4.1
  - syb-0.7.2.1
  - clock-0.8.3
  - th-compat-0.1.3
allow-different-user: true
